### PR TITLE
Multiqc script import and conversion

### PR DESCRIPTION
**Pull request by hassanfa**
This PR adds a standalone script to extract data from multiqc report.

To test this PR on a multiqc json file, or the example provided please do the following:

Tested on the following (which should be fine if vogue is installed):
```
json==2.0.9
logging==0.5.1.2
click==6.7
coloredlogs==9.0
```

Within `vogue`:
1. `git checkout multiqc_script`
2. `cd script`
3. The following will extract results for three sample keys. These keys are based on input file names and how multiqc is handling them. They have nothing to do with actual LIMS ids.

```
./prepare_multiqc.py \
    --multiqc-json multiqc_data.json \
    --output-json sample.json  \
    --log-level DEBUG \
    --decompose \
    --sample ACC5152A10_R \
    --sample ACC5152A1_R \
    --sample ACC5152A1_R_FR
```

### CODE REVIEW

**Comment by hassanfa** [comment]
@henrikstranneheim I'll add some tests.

This is basically a plugin for Vogue. It can be either added to workflows or Vogue. So it would be something like this if housekeeper is aware of multiqc files:
```
#cg or some other solution will call this script on multiqc_data.json
./prepare_multiqc.py \
    --multiqc-json multiqc_data.json \
    --output-json sample.json  \
    --log-level DEBUG \
    --decompose \
    --sample ACC5152A10_R
# the output file will be ACC5152A10_R.sample.json
# cg then will call vogue load analysis sample,
# and this will load QC metrics for ACC5152A10 to trendingdb
vogue load analysis sample \
    --sample-id ACC5152A10 \
    --analysis-config ACC5152A10_R.sample.json \
    --analysis-type QC
```

**Comment by henrikstranneheim** [comment]
Excellent!

**Comment by hassanfa** [comment]
@henrikstranneheim 
added test for the functions and changed it a bit.

```
============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
cachedir: .pytest_cache
plugins: cov-2.6.1
collecting ... collected 5 items

test_prepare_multiqc.py::test_read_multiqc PASSED                        [ 20%]
test_prepare_multiqc.py::test_validate_multiqc PASSED                    [ 40%]
test_prepare_multiqc.py::test_extract_analysis PASSED                    [ 60%]
test_prepare_multiqc.py::test_write_json PASSED                          [ 80%]
test_prepare_multiqc.py::test_write_json_per_sample PASSED               [100%]

---------- coverage: platform darwin, python 3.6.7-final-0 -----------
Name                      Stmts   Miss  Cover
---------------------------------------------
prepare_multiqc.py           93     40    57%
test_prepare_multiqc.py      59      0   100%
---------------------------------------------
TOTAL                       152     40    74%


=========================== 5 passed in 0.67 seconds ===========================
```

**Comment by hassanfa** [comment]
@henrikstranneheim changed style a bit and removed one liners.

**Comment by henrikstranneheim** [comment]
Great Work!

**Comment by mayabrandi** [comment]
Yep. Super duper. We are getting closer!

**Pull request merged**
