### PR TITLE
Collapses the get date functions into one function

### PR DESCRIPTION
**Pull request by moonso**
I noticed that the 4 get_date functions where very similar so I collapsed them into one function.
This will make it fairly easy to extend as well.

Check what you think!

### CODE REVIEW

**Comment by mayabrandi** [comment]
It doesn't feel good to diss this when you spent so much time on it.. But I really think they should be separate functions. Reason:

In general I prefer to have simple functions and mainly one function per field in the database (in some cases this is not appropriate though). 

In other projects, I have gone from having complex and general functions that were used in many places, to start making more and more specific and simple functions. The reason is I find it a lot simpler to maintain and debug like that. 

If say we want to add another date to the database.. Its more probable that we will crash the code for some of the other dates if they are all created in the same function. Specially when time goes and you forget about the smart way you built the function from the beginning. Im making small functions to be kind to myself in the future when I get back to the code and dont remember anything.

If the get_date functions were more or less identical, as with the "get_nr_of_days functions" then I would totally agree on that they should be merged. But these functions are deferring enough for me to prefer them to be separate. 

This is just me.. Im glad to hear any arguments against :)

**Comment by moonso** [comment]
It is no problem for me if we not use these changes! 
I don't think that the function is smart or complicated and it is fairly easy to test. 
The problem is that the four functions are more or less doing exactly the same thing but in four different ways which is very confusing when reading the code.
if this suggestion is even more confusing we should at least rewrite the functions so that they look the same.

**Comment by mayabrandi** [comment]
My opinion is strong about this but, but what does it matter when the majority is agains me! :) Lets go for this version!

I don't have time to work on this Pull request today though. Ill read it through on Friday. 

Thanks for cleaning the functions up @moonso

**Comment by mayabrandi** [comment]
We have agreed on using separate functions to handle these

**Pull request closed without merging**
