### PR TITLE
Some formatting to prepare for github actions

### PR DESCRIPTION
**Pull request by hassanfa**
Run code formatter `yapf` on all Vogue python code base.

### CODE REVIEW

**Comment by hassanfa** [comment]
@mayabrandi this is quite tiny. I just autoformatted code. So when we add github actions it doesn't complain. :-)

**Comment by hassanfa** [comment]
It shows 56 files changed, but it is just empty spaces and prettifying code

**Comment by northwestwitch** [comment]
I'm approving this one as well, looks many small changes

**Review by northwestwitch — APPROVED** [review]
Looks good

**Pull request merged**
