### PR TITLE
docs, rtfd

### LINKED ISSUE #193: Autobuild Vogue API guide and general docs in RTFD (Readthedocs)
It will live here: https://vogue.readthedocs.io/en/latest/

### PR DESCRIPTION
**Pull request by hassanfa**
Added:

autodoc build using Sphinx: 
image

fixes #193 

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by hassanfa** [comment]
documentations will be built here: https://vogue.readthedocs.io/en/latest/

**Comment by hassanfa** [comment]
This branch will look like this for now: https://vogue.readthedocs.io/en/feat-rtfd/

**Review by mayabrandi — APPROVED** [review]
Cool. I Intend to do the same for cg_lims. Ill mimic what youve done here ;)

**Comment by hassanfa** [comment]
For the record, this is to test waters in creating a comprehensive Vogue documentation. Usage, validation, and implementation documentations should go to atlas.

**Pull request merged**
