### PR TITLE
Option to argument

### PR DESCRIPTION
**Pull request by mayabrandi**

### CODE REVIEW

**Comment by mayabrandi** [comment]
> Is this argument always one? Does Click by default assume it is one or multiple?

The argument is always one string.

**Comment by moonso** [comment]
Click will always assume one argument, otherwise one has to use `multiple=True`

**Comment by hassanfa** [comment]
It doesn't always assume:
```
$vogue load apptag '[{"tag":"MELPCFR030", "category":"wgs"}]' '[{"tag":"MELPCFR030", "category":"wgs"}]'
2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se mongo_adapter.client[41180] INFO Connecting to uri:mongodb://None:None@localhost:27017
2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se mongo_adapter.client[41180] INFO Connection established
2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se vogue.adapter.plugin[41180] INFO Use database trending.
Usage: vogue load apptag [OPTIONS] APPLICATION_TAGS
Try "vogue load apptag --help" for help.

Error: Got unexpected extra argument ([{"tag":"MELPCFR030", "category":"wgs"}])
```

This fails on two arguments.

**Comment by hassanfa** [comment]
A bit more context: `https://click.palletsprojects.com/en/7.x/arguments/`. Probably a `nargs=1` is needed.

**Comment by mayabrandi** [comment]
> It doesn't always assume:
> 
> ```
> $vogue load apptag '[{"tag":"MELPCFR030", "category":"wgs"}]' '[{"tag":"MELPCFR030", "category":"wgs"}]'
> 2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se mongo_adapter.client[41180] INFO Connecting to uri:mongodb://None:None@localhost:27017
> 2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se mongo_adapter.client[41180] INFO Connection established
> 2019-02-22 11:00:13 130-229-8-184-dhcp.wlan.ki.se vogue.adapter.plugin[41180] INFO Use database trending.
> Usage: vogue load apptag [OPTIONS] APPLICATION_TAGS
> Try "vogue load apptag --help" for help.
> 
> Error: Got unexpected extra argument ([{"tag":"MELPCFR030", "category":"wgs"}])
> ```
> This fails on two arguments.

But one should not give two stings as argument. It assumes this:

vogue load apptag '[{"tag":"MELPCFR030", "category":"wgs"}, {"tag":"MELPCFR030", "category":"wgs"}]'

**Comment by moonso** [comment]
Yes @hassanfa , your example fails because it is not **one** json string but two so the program behaves as expected

**Comment by hassanfa** [comment]
> Yes @hassanfa , your example fails because it is not **one** json string but two so the program behaves as expected

ok!

**Pull request merged**
