### PR TITLE
Solved the app out of context error

### PR DESCRIPTION
**Pull request by ingkebil**
Solved the app out of context error.

Instead, it seems now no routes can be found.

How to test:
0. clone the repo to ~/git/yourname/
1. cd ~/git/yourname/vogue
2. source activate S_vogue
3. pip install -e .
4. supervisorctl restart vogue-stage

go to https://vogue-stage.scilifelab.se. It works :) Now even with debug toolbar enabled with `FLASK_DEBUG=1` in supervisor's config.

### CODE REVIEW

**Comment by ingkebil** [comment]
Also: I get this error with and without the ProxyFix enabled.

**Comment by northwestwitch** [comment]
Does it work? Because as it is described here: https://stackoverflow.com/questions/26211267/nginx-flask-gunicorn-502-error

Looks like that the ProxyFix is used not in the app, but in the file executed by gunicorn for starting the app.

**Comment by ingkebil** [comment]
We're starting gunicorn with `gunicorn vogue.servers.view:app`, so that's the same file for us.

**Comment by ingkebil** [comment]
Found it. It's because app is defined on a global level in views and there is never a call to create_app.

**Comment by northwestwitch** [comment]
current_app saved me so many times :)

> Found it. It's because app is defined on a global level in views and there is never a call to create_app.

Oh yes, when you call views you call each of them as a method, you are not running the entire file from the beginning I guess

**Comment by ingkebil** [comment]
OK, the longer explanation:
vogue server was only tested by running it from the CLI. The CLI explicitly passes the `vogue.server.create_app` function to the FlaskGroup that creates the CLI. For the server running behind gunicorn, create_app was never invoked and no app was instantiated. Gunicorn was passed `vogue.server.views:app`, which does exist and is None. Now, gunicorn is passed `vogue.server.auto:app` which is an app created with `create_app`. And it's voodoo! it works!

**Comment by northwestwitch** [comment]
Glad that it works, I was starting to feel a bit guilty because I was the one who suggested to update to Flask 1.0.2 and @mayabrandi had all that code changed! :)

**Comment by mayabrandi** [comment]
🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻 Youre the best Kenny!

**Pull request merged**
